services:
  database:
    image: mariadb
    volumes:
      - ./grid.sql:/docker-entrypoint-initdb.d/grid.sql
      - database:/var/lib/mysql
    environment:
      - MARIADB_USER=${DATABASE_USERNAME}
      - MARIADB_PASSWORD=${DATABASE_PASSWORD}
      - MARIADB_DATABASE=${DATABASE_DATABASE}
      - MARIADB_RANDOM_ROOT_PASSWORD=1
    healthcheck:
      test:
        [
          "CMD",
          "/usr/local/bin/healthcheck.sh",
          "--su-mysql",
          "--connect",
        ]
      interval: 5s
      timeout: 5s
      retries: 5

  python-api:
    build:
      target: python
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./.env:/var/grid/.env
      - ./grid:/var/grid/grid
    command: uvicorn grid.api.main:app --host 0.0.0.0 --port 8000 --reload
    working_dir: /var/grid

  python-updater:
    build:
      target: python
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./.env:/var/grid/.env
      - ./grid:/var/grid/grid
      - ./update.py:/var/grid/update.py
    command: sh -c "python /var/grid/update.py && sleep infinity"
    working_dir: /var/grid

  nuxt:
    build:
      target: nuxt
    environment:
      - API_BASE_URL=http://python-api:8000

  web:
    build:
      target: web
    ports:
      - "9714:80"
    depends_on:
      - nuxt
      - python-api

volumes:
  database:
